all:
	@echo "This tool is bundled for convenience, a more up to date version might exist. See:"
	@echo "  - https://github.com/OtherCrashOverride/odroid-go-firmware"
	@echo "  - https://github.com/ducalex/odroid-go-multi-firmware"
	gcc -g main.c crc32.c -o mkfw
