#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#
#EXTRA_COMPONENT_DIRS := 
PROJECT_NAME := gnuboy-go

include $(IDF_PATH)/make/project.mk
