#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#
#EXTRA_COMPONENT_DIRS := 
PROJECT_NAME := gnuboy-go

EXTRA_COMPONENT_DIRS := ../components
include $(IDF_PATH)/make/project.mk
