#
# Component Makefile
#

COMPONENT_SRCDIRS := src src/littlefs

COMPONENT_ADD_INCLUDEDIRS := include

COMPONENT_PRIV_INCLUDEDIRS := src

COMPONENT_SUBMODULES := src/littlefs

CFLAGS += \
	-DLFS_CONFIG=lfs_config.h

ifdef CONFIG_LITTLEFS_FCNTL_GET_PATH
	CFLAGS += \
		-DF_GETPATH=$(CONFIG_LITTLEFS_FCNTL_F_GETPATH_VALUE)
endif

ifdef CONFIG_LITTLEFS_MULTIVERSION
	CFLAGS += \
		-DLFS_MULTIVERSION
endif
