name: ci

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build
      uses: docker/build-push-action@v2
      with:
        context: .
        tags: retro-go:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
        load: true

    - name: Extract binaries from docker image
      run: |
        docker run --rm -v $(pwd)/build:/build retro-go:latest sh -c "cp /app/*.fw /build"

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: binaries
        path: build/*.fw
